# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-posted_time'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('design', models.IntegerField(choices=[(8, '8'), (2, '2'), (3, '3'), (9, '9'), (10, '10'), (1, '1'), (4, '4'), (5, '5'), (7, '7'), (6, '6')], default=0)),
                ('usability', models.IntegerField(choices=[(8, '8'), (2, '2'), (3, '3'), (9, '9'), (10, '10'), (1, '1'), (4, '4'), (5, '5'), (7, '7'), (6, '6')], default=0)),
                ('content', models.IntegerField(choices=[(8, '8'), (2, '2'), (3, '3'), (9, '9'), (10, '10'), (1, '1'), (4, '4'), (5, '5'), (7, '7'), (6, '6')], default=0)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='award.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
