# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-09 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.IntegerField(choices=[(6, '6'), (9, '9'), (8, '8'), (10, '10'), (5, '5'), (7, '7'), (3, '3'), (1, '1'), (4, '4'), (2, '2')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(choices=[(6, '6'), (9, '9'), (8, '8'), (10, '10'), (5, '5'), (7, '7'), (3, '3'), (1, '1'), (4, '4'), (2, '2')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(choices=[(6, '6'), (9, '9'), (8, '8'), (10, '10'), (5, '5'), (7, '7'), (3, '3'), (1, '1'), (4, '4'), (2, '2')], default=0),
        ),
    ]
