# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_auto_20181228_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.IntegerField(choices=[(6, '6'), (9, '9'), (5, '5'), (4, '4'), (3, '3'), (1, '1'), (2, '2'), (8, '8'), (7, '7'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(choices=[(6, '6'), (9, '9'), (5, '5'), (4, '4'), (3, '3'), (1, '1'), (2, '2'), (8, '8'), (7, '7'), (10, '10')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(choices=[(6, '6'), (9, '9'), (5, '5'), (4, '4'), (3, '3'), (1, '1'), (2, '2'), (8, '8'), (7, '7'), (10, '10')], default=0),
        ),
    ]
