# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0041_auto_20181228_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (6, '6'), (9, '9'), (8, '8'), (10, '10'), (4, '4'), (7, '7'), (2, '2'), (1, '1')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (6, '6'), (9, '9'), (8, '8'), (10, '10'), (4, '4'), (7, '7'), (2, '2'), (1, '1')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(choices=[(3, '3'), (5, '5'), (6, '6'), (9, '9'), (8, '8'), (10, '10'), (4, '4'), (7, '7'), (2, '2'), (1, '1')], default=0),
        ),
    ]
